import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import "./globals.css";
import ReduxProvider from '@/redux/provider';
import './globals.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arogya",
  description: "Generated by create next app",
  title: "Arogyaa Web App",
  description: "Online Doctor Consulation",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>{children}</body>
      </UserProvider>
   <body className={inter.className}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
